frameworkVersion: '2.18.0'

org: mikitane
app: shopping-lists-backend
service: auth

provider:
  name: aws
  region: eu-west-1

resources:
  Resources:
    MainUserPool:
      Type: 'AWS::Cognito::UserPool'
      Properties:
        UserPoolName: ${self:service}-${opt:stage}-MainUserPool
  Outputs:
    MainUserPoolArn:
      Value: !GetAtt MainUserPool.Arn
      Export:
        Name: ${self:service}-${opt:stage}-MainUserPool-Arn


