org: mikitane
app: shopping-lists-backend
service: shopping-lists
frameworkVersion: '2.18.0'

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    MAIN_TABLE: db-${opt:stage}-MainTable
    # AWS_REGION: ${self:custom.region}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - !ImportValue ${self:provider.environment.MAIN_TABLE}-Arn
        # - ${cf:${self:provider.environment.DB_SERVICE}.MainTableArn}

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
  region: ${opt:region, self:provider.region}

plugins:
  - serverless-webpack

functions:
  createShoppingList:
    handler: 'src/functions/createShoppingList.createShoppingList'
    events:
      - http:
          method: post
          path: shopping-list
