org: mikitane
app: shopping-lists-backend
service: shopping-lists
frameworkVersion: '2.18.0'

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        Fn::GetAtt:
          - ${cf:db-${opt:stage}.MainTable}
          - Arn

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

plugins:
  - serverless-webpack

functions:
  createGame:
    handler: 'src/functions/createShoppingList.createShoppingList'
    events:
      - http:
          method: post
          path: shopping-list
